# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Translation Check

on: [push, pull_request]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r validator/requirements.txt
    - name: Translation Validator
      id: translationvalidat
      continue-on-error: true # Continue to Output Step anyway
      run: |
        set +e
        cd validator
        python main.py "../The_Colonists_Translation_Data_Italian.csv"
        if [ $? -ne 0 ]; then
          echo "Translation Check Command failed, setting status to failure"
          echo "status=failure" >> $GITHUB_ENV
        else
          echo "Translation Check Command succeeded, setting status to success"
          echo "status=success" >> $GITHUB_ENV
        fi
    - name: Output result
      run: |
        cd validator
        cat result.txt
        echo "Translation Check Status is ${{ env.status }}"
        if [ "${{ env.status }}" = "failure" ]; then
          echo "Found failure status, exiting with 1..."
          echo "::error::Previous step failed"
          exit 1
        fi
